### ISSUE TITLE
Allow to specify which labels/tags/metadata to use for grouping hosts

### ISSUE THREAD

**Issue by guidograzioli** [kubevirt/kubevirt.core#25]
##### SUMMARY

Other cloud collections ([aws sample](https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html#parameter-keyed_groups)) allow to list the labels for forming host groups, using the `keyed_groups`(list) paramenter. It would be nice to have it in the kubevirt_inventory too

##### ISSUE TYPE
 - Feature Idea

**Comment by 0xFelix** [comment]
Fixed by #77
